const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export const env = {
  SUPABASE_URL: SUPABASE_URL || "",
  SUPABASE_ANON_KEY: SUPABASE_ANON_KEY || "",
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  ADMIN_BEARER_TOKEN: process.env.ADMIN_BEARER_TOKEN,
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
};
